# Generated by Django 5.1.7 on 2025-03-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhello', '0002_course_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Course_table',
        ),
    ]
